// Generated by ig-codegen from edqm-standardterms 1.0.1. Do not edit directly.
package io.github.dizuker.medrezeptetofhir.edqm;

import java.util.Optional;
import org.hl7.fhir.r4.model.Coding;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

public final class EdqmStandardTerms {
  private EdqmStandardTerms() {}

  public static final class CodeSystems {
    private CodeSystems() {}

    /**
     * The canonical URL {@code http://standardterms.edqm.eu}.
     *
     * @return {@code http://standardterms.edqm.eu}
     */
    public static String edqmStandardterms() {
      return "http://standardterms.edqm.eu";
    }

    public enum EdqmStandardterms {
      _14001000("14001000", "Cream + pessary"),

      _14002000("14002000", "Cutaneous solution + medicated sponge"),

      _14003000("14003000", "Gastro-resistant tablet + rectal suspension"),

      _14004000("14004000", "Vaginal capsule, soft + vaginal cream"),

      _14005000("14005000", "Vaginal cream + vaginal tablet"),

      _14006000("14006000", "Effervescent granules + film-coated tablet"),

      _14007000("14007000", "Effervescent tablet + film-coated tablet"),

      _14008000("14008000", "Tablet + vaginal tablet"),

      _14009000("14009000", "Cream + vaginal capsule, soft"),

      _14010000("14010000", "Cream + vaginal tablet"),

      _14011000("14011000", "Film-coated tablet + pessary"),

      _14012000("14012000", "Capsule, soft + tablet"),

      _14013000("14013000", "Capsule, hard + tablet"),

      _14014000("14014000", "Film-coated tablet + tablet"),

      _14015000("14015000", "Ointment + vaginal tablet"),

      _14016000("14016000", "Effervescent granules + gastro-resistant tablet"),

      _14017000("14017000", "Eye drops, solution + eye ointment"),

      _50001500("50001500", "Concentrate and diluent for solution for infusion"),

      _13086000("13086000", "Concentrate and solvent for concentrate for oral spray, suspension"),

      _50002000("50002000", "Concentrate and solvent for concentrate for solution for infusion"),

      _50003000("50003000", "Concentrate and solvent for cutaneous solution"),

      _50004000("50004000", "Concentrate and solvent for cutaneous use"),

      _13143000("13143000", "Concentrate and solvent for dispersion for injection"),

      _13153000("13153000", "Concentrate and solvent for emulsion for injection"),

      _50005000("50005000", "Concentrate and solvent for injection"),

      _13144000("13144000", "Concentrate and solvent for intravesical solution"),

      _13160000("13160000", "Concentrate and solvent for oral solution"),

      _50006000("50006000", "Concentrate and solvent for solution for infusion"),

      _50007000("50007000", "Concentrate and solvent for solution for injection"),

      _50007500("50007500", "Concentrate and solvent for solution for injection/infusion"),

      _50008000("50008000", "Concentrate and solvent for suspension for injection"),

      _10707000("10707000", "Ear drops, powder and solvent for suspension"),

      _13157000("13157000", "Effervescent granules and suspension for oral suspension"),

      _13119000("13119000", "Effervescent powder and powder for oral suspension"),

      _13150000("13150000", "Effervescent powder and suspension for oral suspension"),

      _13092000("13092000", "Emulsion and lyophilisate for suspension for injection"),

      _50021500("50021500", "Emulsion and suspension for emulsion for injection"),

      _11604000("11604000", "Endotracheopulmonary instillation, powder and solvent for solution"),

      _11605000("11605000", "Endotracheopulmonary instillation, powder and solvent for suspension"),

      _10606000("10606000", "Eye drops, powder and solvent for solution"),

      _10607000("10607000", "Eye drops, powder and solvent for suspension"),

      _12109500("12109500", "Fibrin sealant-powder and solvent for fibrin sealant"),

      _50078000("50078000", "Gas and solvent for dispersion for injection/infusion"),

      _13138000("13138000", "Gastro-resistant powder and solvent for oral suspension"),

      _50026500("50026500", "Granules and solvent for oral suspension"),

      _50027000("50027000", "Granules and solvent for suspension for injection"),

      _13117000("13117000", "Lyophilisate and solvent for emulsion for injection"),

      _13088000("13088000", "Lyophilisate and solvent for oculonasal suspension"),

      _13093000("13093000", "Lyophilisate and solvent for oral suspension"),

      _11214500("11214500", "Lyophilisate and solvent for solution for injection"),

      _50034500("50034500", "Lyophilisate and solvent for suspension for injection"),

      _11214700("11214700", "Lyophilisate and suspension for suspension for injection"),

      _10800500("10800500", "Nasal drops, lyophilisate and solvent for suspension"),

      _50047650("50047650", "Nasal drops, powder and solvent for solution"),

      _13097000("13097000", "Nasal spray, lyophilisate and solvent for suspension"),

      _50041200("50041200", "Powder and gel for gel"),

      _13101000("13101000", "Powder and solution for bee-hive dispersion"),

      _13081000("13081000", "Powder and solution for bee-hive solution"),

      _10412000("10412000", "Powder and solution for dental cement"),

      _50041500("50041500", "Powder and solution for solution for injection"),

      _13121000("13121000", "Powder and solution for suspension for injection"),

      _50042000("50042000", "Powder and solvent for concentrate for solution for infusion"),

      _50044000("50044000", "Powder and solvent for cutaneous solution"),

      _50071000("50071000", "Powder and solvent for dental gel"),

      _50044500("50044500", "Powder and solvent for dispersion for injection"),

      _50044700("50044700", "Powder and solvent for emulsion for injection"),

      _11702000("11702000", "Powder and solvent for endocervical gel"),

      _50045000("50045000", "Powder and solvent for endosinusial solution"),

      _50045500("50045500", "Powder and solvent for epilesional solution"),

      _50046000("50046000", "Powder and solvent for gingival gel"),

      _11304000("11304000", "Powder and solvent for implantation paste"),

      _50047000("50047000", "Powder and solvent for intraocular instillation solution"),

      _50047500("50047500", "Powder and solvent for intravesical solution"),

      _50047600("50047600", "Powder and solvent for intravesical suspension"),

      _50047700("50047700", "Powder and solvent for nebuliser solution"),

      _10114000("10114000", "Powder and solvent for oral solution"),

      _10115000("10115000", "Powder and solvent for oral suspension"),

      _50048000("50048000", "Powder and solvent for prolonged-release suspension for injection"),

      _12116000("12116000", "Powder and solvent for sealant"),

      _11214000("11214000", "Powder and solvent for solution for infusion"),

      _11207000("11207000", "Powder and solvent for solution for injection"),

      _50080000("50080000", "Powder and solvent for solution for injection/infusion"),

      _50048270("50048270", "Powder and solvent for solution for injection/skin-prick test"),

      _11208000("11208000", "Powder and solvent for suspension for injection"),

      _10115500("10115500", "Powder and solvent for syrup"),

      _50048500("50048500", "Powder and suspension for suspension for injection"),

      _13062000("13062000", "Powder for concentrate and solution for solution for infusion"),

      _50048600(
          "50048600", "Powder, dispersion and solvent for concentrate for dispersion for infusion"),

      _50055350("50055350", "Powder, solvent and matrix for implantation matrix"),

      _50062000("50062000", "Suspension and effervescent granules for oral suspension"),

      _50062500("50062500", "Suspension and solution for spray"),

      _50062750("50062750", "Suspension and solvent for suspension for injection"),

      _50065000("50065000", "Tablet and powder for oral solution"),

      _50064000("50064000", "Tablet and solvent for rectal suspension"),

      _11210500("11210500", "Solution for infusion in administration system"),

      _13053000("13053000", "Solution for injection in administration system"),

      _13057000(
          "13057000",
          "Powder and solvent for prolonged-release suspension for injection in pre-filled syringe"),

      _13060000("13060000", "Powder for oral/rectal suspension in sachet"),

      _13064000("13064000", "Suspension for injection in pre-filled injector"),

      _13068000("13068000", "Solution for injection in pre-filled injector"),

      _13069000("13069000", "Gel in sachet"),

      _13071000("13071000", "Solution for injection in dose-dispenser cartridge"),

      _13075000("13075000", "Oral suspension in pre-filled oral applicator"),

      _13083000("13083000", "Bee-hive dispersion in sachet"),

      _13090000("13090000", "Granules in single-dose container"),

      _13094000("13094000", "Syrup in sachet"),

      _13095000("13095000", "Emulsion for infusion in administration system"),

      _13103000("13103000", "Cutaneous solution in single-dose container"),

      _13104000("13104000", "Eye drops, emulsion in single-dose container"),

      _13108000(
          "13108000", "Powder and solvent for suspension for injection in multidose container"),

      _13109000("13109000", "Solution for injection in multidose container"),

      _13110000("13110000", "Suspension for injection in multidose container"),

      _13112000("13112000", "Prolonged-release suspension for injection in pre-filled pen"),

      _13120000("13120000", "Nasal powder in single-dose container"),

      _13122000("13122000", "Solution for infusion in cartridge"),

      _13130000("13130000", "Oral powder in single-dose container"),

      _13137000("13137000", "Transdermal gel in sachet"),

      _13146000("13146000", "Oral solution in multidose container with metering pump"),

      _13147000("13147000", "Powder for oral suspension in sachet"),

      _13155000("13155000", "Film-coated granules in single-dose container"),

      _13161000("13161000", "Dispersion for injection in pre-filled syringe"),

      _50001250("50001250", "Coated granules in sachet"),

      _50017200("50017200", "Ear drops, solution in single-dose container"),

      _50017550("50017550", "Ear drops, suspension in single-dose container"),

      _50021250("50021250", "Emulsion for injection/infusion in pre-filled syringe"),

      _50022500("50022500", "Eye drops, prolonged-release solution in single-dose container"),

      _50023000("50023000", "Eye drops, solution in single-dose container"),

      _50023100("50023100", "Eye drops, suspension in single-dose container"),

      _50023300("50023300", "Eye gel in single-dose container"),

      _50023400("50023400", "Eye ointment in single-dose container"),

      _50023700("50023700", "Film-coated tablet and gastro-resistant granules in sachet"),

      _50026150("50026150", "Gastro-resistant granules for oral suspension in sachet"),

      _50026400("50026400", "Gel in pressurised container"),

      _50029170("50029170", "Granules for oral solution in sachet"),

      _50029200("50029200", "Granules for oral suspension in sachet"),

      _50029550("50029550", "Granules in sachet"),

      _50029700("50029700", "Herbal tea in bag"),

      _50029750("50029750", "Implant in pre-filled syringe"),

      _50033500("50033500", "Intravitreal implant in applicator"),

      _50036200("50036200", "Nasal drops, solution in single-dose container"),

      _50037250("50037250", "Nasal spray, solution in single-dose container"),

      _50037450("50037450", "Nebuliser solution in single-dose container"),

      _50037600("50037600", "Oral emulsion in sachet"),

      _50037700("50037700", "Oral paste in sachet"),

      _50037800("50037800", "Oral powder in sachet"),

      _50038600("50038600", "Oral solution in sachet"),

      _50038650("50038650", "Oral solution in single-dose container"),

      _50038700("50038700", "Oral suspension in sachet"),

      _50039300("50039300", "Oromucosal powder in pouch"),

      _50041000("50041000", "Pillules in single-dose container"),

      _50048010(
          "50048010",
          "Powder and solvent for prolonged-release suspension for injection in pre-filled pen"),

      _50048050("50048050", "Powder and solvent for solution for injection in cartridge"),

      _50048150("50048150", "Powder and solvent for solution for injection in pre-filled pen"),

      _50048250("50048250", "Powder and solvent for solution for injection in pre-filled syringe"),

      _50048300(
          "50048300", "Powder and solvent for suspension for injection in pre-filled syringe"),

      _50048400("50048400", "Powder and solvent in pre-filled syringe for solution for injection"),

      _50052500("50052500", "Powder for oral solution in sachet"),

      _50056150("50056150", "Prolonged-release granules for oral suspension in sachet"),

      _50056200("50056200", "Prolonged-release granules in sachet"),

      _50056250("50056250", "Prolonged-release suspension for injection in pre-filled syringe"),

      _50056600(
          "50056600", "Solution and suspension for suspension for injection in pre-filled syringe"),

      _50058500("50058500", "Solution for infusion in pre-filled syringe"),

      _50060100("50060100", "Solution for injection in cartridge"),

      _50060150("50060150", "Solution for injection in needle-free injector"),

      _50060200("50060200", "Solution for injection in pre-filled pen"),

      _50060300("50060300", "Solution for injection in pre-filled syringe"),

      _50060400(
          "50060400", "Solution for injection in pre-filled syringe with automatic needle guard"),

      _50060500("50060500", "Solution for injection/infusion in pre-filled syringe"),

      _50063100("50063100", "Suspension for injection in cartridge"),

      _50063200("50063200", "Suspension for injection in pre-filled pen"),

      _50063300("50063300", "Suspension for injection in pre-filled syringe"),

      _30001000("30001000", "Ampoule"),

      _30002000("30002000", "Applicator"),

      _30003000("30003000", "Automatic injection device"),

      _30004000("30004000", "Bag"),

      _30005000("30005000", "Balling gun"),

      _30006000("30006000", "Barrel"),

      _30007000("30007000", "Blister"),

      _30008000("30008000", "Bottle"),

      _30009000("30009000", "Box"),

      _30010000("30010000", "Brush"),

      _30011000("30011000", "Brush applicator"),

      _30012000("30012000", "Cannula"),

      _30013000("30013000", "Cap"),

      _30014000("30014000", "Cartridge"),

      _30015000("30015000", "Child-resistant closure"),

      _30016000("30016000", "Cup"),

      _30017000("30017000", "Dabbing applicator"),

      _30018000("30018000", "Dart"),

      _30019000("30019000", "Dredging applicator"),

      _30020000("30020000", "Dredging container"),

      _30021000("30021000", "Drench gun"),

      _30022000("30022000", "Dropper applicator"),

      _30023000("30023000", "Dropper container"),

      _30023005("30023005", "Fixed cryogenic vessel"),

      _30024000("30024000", "Gas cylinder"),

      _30025000("30025000", "High pressure transdermal delivery device"),

      _30026000("30026000", "Implanter"),

      _30026500("30026500", "Inhaler"),

      _30027000("30027000", "In-ovo injection device"),

      _30028000("30028000", "Injection needle"),

      _30029000("30029000", "Injection syringe"),

      _30030000("30030000", "Internal graduated calibration chamber"),

      _30031000("30031000", "Intramammary syringe"),

      _30032000("30032000", "Jar"),

      _30033000("30033000", "Measuring device"),

      _30034000("30034000", "Measuring spoon"),

      _30035000("30035000", "Metering pump"),

      _30036000("30036000", "Metering valve"),

      _30036005("30036005", "Mobile cryogenic vessel"),

      _30037000("30037000", "Mouthpiece"),

      _30038000("30038000", "Multidose container"),

      _30039000("30039000", "Multidose container with airless pump"),

      _30040000("30040000", "Multipuncturer"),

      _30041000("30041000", "Nasal applicator"),

      _30042000("30042000", "Nebuliser"),

      _30043000("30043000", "Needle applicator"),

      _30044000("30044000", "Nozzle"),

      _30045000("30045000", "Oral syringe"),

      _30046000("30046000", "Pipette"),

      _30047000("30047000", "Pipette applicator"),

      _13142000("13142000", "Pouch"),

      _30048000("30048000", "Pour-on container"),

      _30049000("30049000", "Pre-filled gastroenteral tube"),

      _30050000("30050000", "Pre-filled pen"),

      _30051000("30051000", "Pre-filled syringe"),

      _30052000("30052000", "Pressurised container"),

      _30053000("30053000", "Prick test applicator"),

      _30054000("30054000", "Sachet"),

      _30055000("30055000", "Scarifier"),

      _30056000("30056000", "Screw cap"),

      _30057000("30057000", "Single-dose container"),

      _30058000("30058000", "Spatula"),

      _30059000("30059000", "Spot-on applicator"),

      _30060000("30060000", "Spray container"),

      _30061000("30061000", "Spray pump"),

      _30062000("30062000", "Spray valve"),

      _30063000("30063000", "Stab vaccinator"),

      _30064000("30064000", "Stopper"),

      _30064500("30064500", "Straw"),

      _30065000("30065000", "Strip"),

      _30066000("30066000", "Tablet container"),

      _30067000("30067000", "Tube"),

      _30068000("30068000", "Vaginal sponge applicator"),

      _30069000("30069000", "Vial"),

      _30000500("30000500", "Administration system"),

      _30011500("30011500", "Calendar package"),

      _30043500("30043500", "Needle-free injector"),

      _30053500("30053500", "Roll-on container"),

      _30039500("30039500", "Multidose container with pump"),

      _30015500("30015500", "Container"),

      _30039400("30039400", "Multidose container with metering pump"),

      _30045500("30045500", "Pack"),

      _13070000("13070000", "Valve"),

      _13072000("13072000", "Oral applicator"),

      _30018200("30018200", "Dose dispenser"),

      _13059000("13059000", "Unit-dose blister"),

      _13063000("13063000", "Pre-filled injector"),

      _13073000("13073000", "Pre-filled oral syringe"),

      _13074000("13074000", "Pre-filled oral applicator"),

      _30018300("30018300", "Dose-dispenser cartridge"),

      _13114000("13114000", "Pen"),

      _13125000("13125000", "Wrapper"),

      _13132000("13132000", "Lid"),

      _13131000("13131000", "Capsule for opening"),

      _13151000("13151000", "Tablet tube"),

      _13156000("13156000", "Gas cylinder bundle"),

      _15001000("15001000", "Actuation"),

      _15002000("15002000", "Ampoule"),

      _15004000("15004000", "Applicator"),

      _15005000("15005000", "Bag"),

      _15006000("15006000", "Barrel"),

      _15007000("15007000", "Blister"),

      _15008000("15008000", "Block"),

      _15009000("15009000", "Bottle"),

      _15011000("15011000", "Cachet"),

      _15012000("15012000", "Capsule"),

      _15013000("15013000", "Cartridge"),

      _15024000("15024000", "Chewing gum"),

      _15015000("15015000", "Collar"),

      _15016000("15016000", "Container"),

      _15017000("15017000", "Cup"),

      _15018000("15018000", "Cylinder"),

      _15019000("15019000", "Dart"),

      _15021000("15021000", "Dressing"),

      _15022000("15022000", "Drop"),

      _15023000("15023000", "Film"),

      _15025000("15025000", "Implant"),

      _15026000("15026000", "Inhaler"),

      _15027000("15027000", "Insert"),

      _15028000("15028000", "Jar"),

      _15029000("15029000", "Lozenge"),

      _15030000("15030000", "Lyophilisate"),

      _15031000("15031000", "Matrix"),

      _15033000("15033000", "Pad"),

      _15034000("15034000", "Paper"),

      _15035000("15035000", "Pastille"),

      _15036000("15036000", "Patch"),

      _15037000("15037000", "Pen"),

      _15038000("15038000", "Pendant"),

      _15039000("15039000", "Pessary"),

      _15040000("15040000", "Pillule"),

      _15041000("15041000", "Pipette"),

      _15042000("15042000", "Plaster"),

      _15043000("15043000", "Plug"),

      _15044000("15044000", "Pouch"),

      _15061000("15061000", "Puff"),

      _15045000("15045000", "Sachet"),

      _15046000("15046000", "Sponge"),

      _15047000("15047000", "Spoonful"),

      _15048000("15048000", "Stick"),

      _15049000("15049000", "Straw"),

      _15050000("15050000", "Strip"),

      _15051000("15051000", "Suppository"),

      _15062000("15062000", "Swab"),

      _15052000("15052000", "Syringe"),

      _15053000("15053000", "System"),

      _15054000("15054000", "Tablet"),

      _15055000("15055000", "Tag"),

      _15056000("15056000", "Tampon"),

      _15057000("15057000", "Thread"),

      _15058000("15058000", "Tube"),

      _15059000("15059000", "Vessel"),

      _15060000("15060000", "Vial"),

      _10100500("10100500", "Concentrate for oral suspension"),

      _10101000("10101000", "Oral drops, solution"),

      _10102000("10102000", "Oral drops, suspension"),

      _10103000("10103000", "Oral drops, emulsion"),

      _10104000("10104000", "Oral liquid"),

      _10105000("10105000", "Oral solution"),

      _10106000("10106000", "Oral suspension"),

      _10107000("10107000", "Oral emulsion"),

      _10108000("10108000", "Oral gel"),

      _10109000("10109000", "Oral paste"),

      _10110000("10110000", "Powder for oral solution"),

      _10111000("10111000", "Powder for oral suspension"),

      _10112000("10112000", "Granules for oral solution"),

      _10113000("10113000", "Granules for oral suspension"),

      _10116000("10116000", "Lyophilisate for suspension"),

      _10117000("10117000", "Syrup"),

      _10118000("10118000", "Powder for syrup"),

      _10119000("10119000", "Granules for syrup"),

      _10120000("10120000", "Soluble tablet"),

      _10121000("10121000", "Dispersible tablet"),

      _10121500("10121500", "Dispersible tablets for dose dispenser"),

      _10122000("10122000", "Herbal tea"),

      _10201000("10201000", "Oral powder"),

      _10202000("10202000", "Instant herbal tea"),

      _10203000("10203000", "Effervescent powder"),

      _10204000("10204000", "Granules"),

      _10205000("10205000", "Effervescent granules"),

      _10206000("10206000", "Gastro-resistant granules"),

      _10207000("10207000", "Prolonged-release granules"),

      _10208000("10208000", "Modified-release granules"),

      _10209000("10209000", "Cachet"),

      _10210000("10210000", "Capsule, hard"),

      _10211000("10211000", "Capsule, soft"),

      _10212000("10212000", "Gastro-resistant capsule, hard"),

      _10213000("10213000", "Gastro-resistant capsule, soft"),

      _10214000("10214000", "Chewable capsule, soft"),

      _10215000("10215000", "Prolonged-release capsule, hard"),

      _10216000("10216000", "Prolonged-release capsule, soft"),

      _10217000("10217000", "Modified-release capsule, hard"),

      _10218000("10218000", "Modified-release capsule, soft"),

      _10219000("10219000", "Tablet"),

      _10220000("10220000", "Coated tablet"),

      _10221000("10221000", "Film-coated tablet"),

      _10222000("10222000", "Effervescent tablet"),

      _10223000("10223000", "Orodispersible tablet"),

      _10224000("10224000", "Oral lyophilisate"),

      _10225000("10225000", "Gastro-resistant tablet"),

      _10226000("10226000", "Prolonged-release tablet"),

      _10227000("10227000", "Modified-release tablet"),

      _10228000("10228000", "Chewable tablet"),

      _10229000("10229000", "Medicated chewing-gum"),

      _10230000("10230000", "Oral gum"),

      _10230500("10230500", "Pill"),

      _10231000("10231000", "Pillules"),

      _10232000("10232000", "Continuous-release intraruminal device"),

      _10233000("10233000", "Pulsatile-release intraruminal device"),

      _10234000("10234000", "Lick block"),

      _10235000("10235000", "Premix for medicated feeding stuff"),

      _10236000("10236000", "Medicated pellets"),

      _10236100("10236100", "Orodispersible film"),

      _10301000("10301000", "Gargle"),

      _10302000("10302000", "Concentrate for gargle"),

      _10303000("10303000", "Gargle, powder for solution"),

      _10304000("10304000", "Gargle, tablet for solution"),

      _10305000("10305000", "Oromucosal solution"),

      _10306000("10306000", "Oromucosal suspension"),

      _10307000("10307000", "Oromucosal drops"),

      _10308000("10308000", "Oromucosal spray"),

      _10308100("10308100", "Oromucosal spray, emulsion"),

      _10308200("10308200", "Oromucosal spray, solution"),

      _10308300("10308300", "Oromucosal spray, suspension"),

      _10309000("10309000", "Sublingual spray"),

      _10309100("10309100", "Sublingual spray, emulsion"),

      _10309200("10309200", "Sublingual spray, solution"),

      _10309300("10309300", "Sublingual spray, suspension"),

      _10310000("10310000", "Mouthwash"),

      _10311000("10311000", "Mouthwash, tablet for solution"),

      _10312000("10312000", "Gingival solution"),

      _10313000("10313000", "Oromucosal gel"),

      _10314000("10314000", "Oromucosal paste"),

      _10314005("10314005", "Oromucosal ointment"),

      _10314010("10314010", "Oromucosal cream"),

      _10314011("10314011", "Buccal film"),

      _10315000("10315000", "Gingival gel"),

      _10316000("10316000", "Gingival paste"),

      _10317000("10317000", "Oromucosal capsule"),

      _10317500("10317500", "Sublingual film"),

      _10318000("10318000", "Sublingual tablet"),

      _10319000("10319000", "Muco-adhesive buccal tablet"),

      _10320000("10320000", "Buccal tablet"),

      _10321000("10321000", "Lozenge"),

      _10322000("10322000", "Compressed lozenge"),

      _10323000("10323000", "Pastille"),

      _10401000("10401000", "Periodontal powder"),

      _10401500("10401500", "Dental cement"),

      _10402000("10402000", "Dental gel"),

      _10403000("10403000", "Dental stick"),

      _10404000("10404000", "Dental insert"),

      _10405000("10405000", "Dental powder"),

      _10406000("10406000", "Dental solution"),

      _10407000("10407000", "Dental suspension"),

      _10408000("10408000", "Dental emulsion"),

      _10409000("10409000", "Toothpaste"),

      _10410000("10410000", "Periodontal gel"),

      _10411000("10411000", "Periodontal insert"),

      _10413000("10413000", "Powder for dental cement"),

      _10414000("10414000", "Solution for dental cement"),

      _10501000("10501000", "Bath additive"),

      _10502000("10502000", "Cream"),

      _10503000("10503000", "Gel"),

      _10504000("10504000", "Ointment"),

      _10505000("10505000", "Cutaneous paste"),

      _10506000("10506000", "Medicated plaster"),

      _10507000("10507000", "Cutaneous foam"),

      _10508000("10508000", "Shampoo"),

      _10509000("10509000", "Cutaneous spray, solution"),

      _10510000("10510000", "Cutaneous spray, suspension"),

      _10511000("10511000", "Cutaneous spray, powder"),

      _10512000("10512000", "Cutaneous liquid"),

      _10513000("10513000", "Cutaneous solution"),

      _10514000("10514000", "Concentrate for cutaneous solution"),

      _10514500("10514500", "Powder for cutaneous solution"),

      _10515000("10515000", "Cutaneous suspension"),

      _10516000("10516000", "Cutaneous emulsion"),

      _10517000("10517000", "Cutaneous powder"),

      _10517500("10517500", "Cutaneous patch"),

      _10518000("10518000", "Solution for iontophoresis"),

      _10518500("10518500", "Powder for solution for iontophoresis"),

      _10519000("10519000", "Transdermal patch"),

      _10520000("10520000", "Collodion"),

      _10521000("10521000", "Medicated nail lacquer"),

      _10521500("10521500", "Nail solution"),

      _10522000("10522000", "Poultice"),

      _10523000("10523000", "Cutaneous stick"),

      _10524000("10524000", "Cutaneous sponge"),

      _10525000("10525000", "Impregnated dressing"),

      _10526000("10526000", "Collar"),

      _10526500("10526500", "Medicated collar"),

      _10527000("10527000", "Medicated pendant"),

      _10528000("10528000", "Ear tag"),

      _10529000("10529000", "Dip solution"),

      _10530000("10530000", "Dip suspension"),

      _10531000("10531000", "Dip emulsion"),

      _10532000("10532000", "Concentrate for dip solution"),

      _10533000("10533000", "Concentrate for dip suspension"),

      _10534000("10534000", "Concentrate for dip emulsion"),

      _10534500("10534500", "Powder for dip solution"),

      _10535000("10535000", "Concentrate for solution for fish treatment"),

      _10536000("10536000", "Powder for suspension for fish treatment"),

      _10537000("10537000", "Pour-on solution"),

      _10538000("10538000", "Pour-on suspension"),

      _10539000("10539000", "Pour-on emulsion"),

      _10539250("10539250", "Scalp solution"),

      _10539500("10539500", "Scrub"),

      _10540000("10540000", "Spot-on solution"),

      _10541000("10541000", "Spot-on suspension"),

      _10542000("10542000", "Spot-on emulsion"),

      _10543000("10543000", "Teat dip solution"),

      _10544000("10544000", "Teat dip suspension"),

      _10545000("10545000", "Teat dip emulsion"),

      _10546000("10546000", "Teat spray solution"),

      _10546250("10546250", "Transdermal gel"),

      _10546400("10546400", "Transdermal solution"),

      _10546500("10546500", "Transdermal spray, solution"),

      _10547000("10547000", "Transdermal system"),

      _10548000("10548000", "Solution for skin-prick test"),

      _10549000("10549000", "Solution for skin-scratch test"),

      _10550000("10550000", "Plaster for provocation test"),

      _10600500("10600500", "Concentrate for solution for intraocular irrigation"),

      _10601000("10601000", "Eye cream"),

      _10602000("10602000", "Eye gel"),

      _10603000("10603000", "Eye ointment"),

      _10604000("10604000", "Eye drops, solution"),

      _10604500("10604500", "Eye drops, emulsion"),

      _10605000("10605000", "Eye drops, suspension"),

      _10608000("10608000", "Eye drops, solvent for reconstitution"),

      _10609000("10609000", "Eye drops, prolonged-release"),

      _10610000("10610000", "Eye lotion"),

      _10611000("10611000", "Eye lotion, solvent for reconstitution"),

      _10612000("10612000", "Ophthalmic insert"),

      _10613000("10613000", "Ophthalmic strip"),

      _10701000("10701000", "Ear cream"),

      _10702000("10702000", "Ear gel"),

      _10703000("10703000", "Ear ointment"),

      _10704000("10704000", "Ear drops, solution"),

      _10705000("10705000", "Ear drops, suspension"),

      _10706000("10706000", "Ear drops, emulsion"),

      _10708000("10708000", "Ear powder"),

      _10709000("10709000", "Ear spray, solution"),

      _10710000("10710000", "Ear spray, suspension"),

      _10711000("10711000", "Ear spray, emulsion"),

      _10712000("10712000", "Ear wash, solution"),

      _10713000("10713000", "Ear wash, emulsion"),

      _10714000("10714000", "Ear tampon"),

      _10715000("10715000", "Ear stick"),

      _10801000("10801000", "Nasal cream"),

      _10802000("10802000", "Nasal gel"),

      _10803000("10803000", "Nasal ointment"),

      _10804000("10804000", "Nasal drops, solution"),

      _10805000("10805000", "Nasal drops, suspension"),

      _10806000("10806000", "Nasal drops, emulsion"),

      _10807000("10807000", "Nasal powder"),

      _10808000("10808000", "Nasal spray, solution"),

      _10809000("10809000", "Nasal spray, suspension"),

      _10810000("10810000", "Nasal spray, emulsion"),

      _10811000("10811000", "Nasal wash"),

      _10812000("10812000", "Nasal stick"),

      _10900500("10900500", "Intravaginal ring"),

      _10901000("10901000", "Vaginal cream"),

      _10902000("10902000", "Vaginal gel"),

      _10903000("10903000", "Vaginal ointment"),

      _10904000("10904000", "Vaginal foam"),

      _10905000("10905000", "Vaginal solution"),

      _10906000("10906000", "Vaginal suspension"),

      _10907000("10907000", "Vaginal emulsion"),

      _10908000("10908000", "Tablet for vaginal solution"),

      _10909000("10909000", "Pessary"),

      _10910000("10910000", "Vaginal capsule, hard"),

      _10911000("10911000", "Vaginal capsule, soft"),

      _10912000("10912000", "Vaginal tablet"),

      _10913000("10913000", "Effervescent vaginal tablet"),

      _10914000("10914000", "Medicated vaginal tampon"),

      _10915000("10915000", "Vaginal delivery system"),

      _10916000("10916000", "Vaginal sponge"),

      _11001000("11001000", "Rectal cream"),

      _11002000("11002000", "Rectal gel"),

      _11003000("11003000", "Rectal ointment"),

      _11004000("11004000", "Rectal foam"),

      _11005000("11005000", "Rectal solution"),

      _11006000("11006000", "Rectal suspension"),

      _11007000("11007000", "Rectal emulsion"),

      _11008000("11008000", "Concentrate for rectal solution"),

      _11009000("11009000", "Powder for rectal solution"),

      _11010000("11010000", "Powder for rectal suspension"),

      _11011000("11011000", "Tablet for rectal solution"),

      _11012000("11012000", "Tablet for rectal suspension"),

      _11013000("11013000", "Suppository"),

      _11014000("11014000", "Rectal capsule"),

      _11015000("11015000", "Rectal tampon"),

      _11100500("11100500", "Aerosol"),

      _11101000("11101000", "Nebuliser solution"),

      _11102000("11102000", "Nebuliser suspension"),

      _11103000("11103000", "Powder for nebuliser suspension"),

      _11104000("11104000", "Powder for nebuliser solution"),

      _11105000("11105000", "Nebuliser emulsion"),

      _11106000("11106000", "Pressurised inhalation, solution"),

      _11107000("11107000", "Pressurised inhalation, suspension"),

      _11108000("11108000", "Pressurised inhalation, emulsion"),

      _11109000("11109000", "Inhalation powder"),

      _11110000("11110000", "Inhalation powder, hard capsule"),

      _11111000("11111000", "Inhalation powder, pre-dispensed"),

      _11112000("11112000", "Inhalation vapour, powder"),

      _11113000("11113000", "Inhalation vapour, capsule"),

      _11114000("11114000", "Inhalation vapour, solution"),

      _11115000("11115000", "Inhalation vapour, tablet"),

      _11116000("11116000", "Inhalation vapour, ointment"),

      _11117000("11117000", "Inhalation vapour, liquid"),

      _11118000("11118000", "Inhalation gas"),

      _11201000("11201000", "Solution for injection"),

      _11202000("11202000", "Suspension for injection"),

      _11203000("11203000", "Emulsion for injection"),

      _11204000("11204000", "Gel for injection"),

      _11205000("11205000", "Powder for solution for injection"),

      _11206000("11206000", "Powder for suspension for injection"),

      _11208400("11208400", "Powder for prolonged-release suspension for injection"),

      _11208500("11208500", "Prolonged-release suspension for injection"),

      _11209000("11209000", "Concentrate for solution for injection"),

      _11209500("11209500", "Solution for cardioplegia"),

      _11210000("11210000", "Solution for infusion"),

      _11211000("11211000", "Emulsion for infusion"),

      _11211500("11211500", "Powder for dispersion for infusion"),

      _11212000("11212000", "Powder for solution for infusion"),

      _11213000("11213000", "Concentrate for solution for infusion"),

      _11215000("11215000", "Lyophilisate for solution for infusion"),

      _11216000("11216000", "Solvent for parenteral use"),

      _11217000("11217000", "Lyophilisate for solution for injection"),

      _11218000("11218000", "Lyophilisate for suspension for injection"),

      _11301000("11301000", "Implant"),

      _11302000("11302000", "Implantation tablet"),

      _11303000("11303000", "Implantation chain"),

      _11303300("11303300", "Implantation matrix"),

      _11303500("11303500", "Implantation suspension"),

      _11303750("11303750", "Kit for implant"),

      _11401000("11401000", "Solution for peritoneal dialysis"),

      _11402000("11402000", "Solution for haemofiltration"),

      _11403000("11403000", "Solution for haemodiafiltration"),

      _11404000("11404000", "Solution for haemodialysis"),

      _11405000("11405000", "Concentrate for solution for haemodialysis"),

      _11501000("11501000", "Solution for intravesical use"),

      _11502000("11502000", "Bladder irrigation"),

      _11502500("11502500", "Intravesical solution"),

      _11503000("11503000", "Powder for bladder irrigation"),

      _11504000("11504000", "Urethral gel"),

      _11505000("11505000", "Urethral stick"),

      _11601000("11601000", "Endotracheopulmonary instillation, solution"),

      _11602000("11602000", "Endotracheopulmonary instillation, powder for solution"),

      _11603000("11603000", "Endotracheopulmonary instillation, suspension"),

      _11701000("11701000", "Endocervical gel"),

      _11801000("11801000", "Intramammary solution"),

      _11802000("11802000", "Intramammary suspension"),

      _11803000("11803000", "Intramammary emulsion"),

      _11804000("11804000", "Intramammary ointment"),

      _11805000("11805000", "Teat stick"),

      _11901000("11901000", "Intrauterine delivery system"),

      _11902000("11902000", "Intrauterine solution"),

      _11903000("11903000", "Intrauterine suspension"),

      _11904000("11904000", "Intrauterine emulsion"),

      _11905000("11905000", "Intrauterine tablet"),

      _11906000("11906000", "Intrauterine capsule"),

      _12001000("12001000", "Bee-hive strip"),

      _12001500("12001500", "Bee-hive gel"),

      _12002000("12002000", "Bee smoke paper"),

      _12003000("12003000", "Bee smoke stick"),

      _12004000("12004000", "Nebulisation solution"),

      _12100500("12100500", "Absorbable coated sponge"),

      _12101000("12101000", "Denture lacquer"),

      _12102000("12102000", "Anticoagulant and preservative solution for blood"),

      _12103000("12103000", "Solution for blood fraction modification"),

      _12104000("12104000", "Wound stick"),

      _12105000("12105000", "Radiopharmaceutical precursor"),

      _12106000("12106000", "Radionuclide generator"),

      _12107000("12107000", "Kit for radiopharmaceutical preparation"),

      _12108000("12108000", "Gastroenteral solution"),

      _12109000("12109000", "Dispersion"),

      _12109900("12109900", "Frozen solution for sealant"),

      _12110000("12110000", "Gastroenteral suspension"),

      _12111000("12111000", "Gastroenteral emulsion"),

      _12111500("12111500", "Intraperitoneal solution"),

      _12112000("12112000", "Solution for organ preservation"),

      _12113000("12113000", "Irrigation solution"),

      _12114000("12114000", "Stomach irrigation"),

      _12115000("12115000", "Sealant"),

      _12115100("12115100", "Sealant matrix"),

      _12115200("12115200", "Sealant powder"),

      _12115500("12115500", "Solution for perfusion of organs"),

      _12117000("12117000", "Impregnated pad"),

      _12117500("12117500", "Impregnated plug"),

      _12118000("12118000", "Living tissue equivalent"),

      _12118500("12118500", "Lyophilisate for oculonasal suspension"),

      _12119000("12119000", "Medicated sponge"),

      _12120000("12120000", "Intestinal gel"),

      _12130000("12130000", "Medicated thread"),

      _12131000("12131000", "Solution for provocation test"),

      _12301000("12301000", "Medicinal gas, compressed"),

      _12302000("12302000", "Medicinal gas, cryogenic"),

      _12303000("12303000", "Medicinal gas, liquefied"),

      _13001000("13001000", "Concentrate for concentrate for solution for infusion"),

      _13002000("13002000", "Concentrate for nebuliser solution"),

      _13003000("13003000", "Concentrate for oromucosal solution"),

      _13004000("13004000", "Concentrate for suspension for injection"),

      _13005000("13005000", "Dispersion for concentrate for dispersion for infusion"),

      _13006000("13006000", "Ear drops, powder for suspension"),

      _13007000("13007000", "Effervescent granules for oral suspension"),

      _13008000("13008000", "Emulsion for emulsion for injection"),

      _13009000("13009000", "Endotracheopulmonary instillation, powder for suspension"),

      _13010000("13010000", "Eye drops, powder for solution"),

      _13011000("13011000", "Eye drops, powder for suspension"),

      _13012000("13012000", "Gas for dispersion for infusion"),

      _13013000("13013000", "Gas for dispersion for injection"),

      _13014000("13014000", "Gel for gel"),

      _13015000("13015000", "Granules for rectal suspension"),

      _13016000("13016000", "Laryngopharyngeal solution"),

      _13017000("13017000", "Laryngopharyngeal spray, solution"),

      _13018000("13018000", "Matrix for implantation matrix"),

      _13019000("13019000", "Nasal drops, lyophilisate for suspension"),

      _13020000("13020000", "Nasal drops, powder for solution"),

      _13021000("13021000", "Powder for gel"),

      _13022000("13022000", "Powder for dental gel"),

      _13023000("13023000", "Powder for dispersion for injection"),

      _13024000("13024000", "Powder for endocervical gel"),

      _13025000("13025000", "Powder for endosinusial solution"),

      _13026000("13026000", "Powder for gingival gel"),

      _13027000("13027000", "Powder for implantation matrix"),

      _13028000("13028000", "Powder for implantation paste"),

      _13029000("13029000", "Powder for intraocular instillation solution"),

      _13031000("13031000", "Powder for sealant"),

      _13032000("13032000", "Powder for solution for skin-prick test"),

      _13033000("13033000", "Solution for solution for injection"),

      _13034000("13034000", "Solution for spray"),

      _13035000("13035000", "Solvent for..."),

      _13036000("13036000", "Suspension for emulsion for injection"),

      _13037000("13037000", "Suspension for oral suspension"),

      _13038000("13038000", "Suspension for spray"),

      _13039000("13039000", "Suspension for suspension for injection"),

      _13040000("13040000", "Powder for emulsion for injection"),

      _13041000("13041000", "Endosinusial solution"),

      _13042000("13042000", "Epilesional solution"),

      _13043000("13043000", "Implantation paste"),

      _13044000("13044000", "Intraocular instillation solution"),

      _13045000("13045000", "Intravesical suspension"),

      _13046000("13046000", "Coated granules"),

      _13047000("13047000", "Solution for suspension for injection"),

      _13048000("13048000", "Granules for suspension for injection"),

      _13049000("13049000", "Dispersion for injection/infusion"),

      _13050000("13050000", "Gas for dispersion for injection/infusion"),

      _13051000("13051000", "Solution for injection/skin-prick test"),

      _13052000("13052000", "Powder for solution for injection/skin-prick test"),

      _13054000("13054000", "Solution for bee-hive strip"),

      _13055000("13055000", "Solution for use in drinking water/milk"),

      _13056000("13056000", "Powder for solution for fish treatment"),

      _13058000("13058000", "Caplet"),

      _13061000("13061000", "Solution for solution for infusion"),

      _13065000("13065000", "Intramammary gel"),

      _13066000("13066000", "Tablet for cutaneous solution"),

      _13067000("13067000", "Lyophilisate for oral suspension"),

      _13076000("13076000", "Prolonged-release solution for injection"),

      _13077000("13077000", "Urethral emulsion"),

      _13078000("13078000", "Bee-hive solution"),

      _13079000("13079000", "Powder for bee-hive solution"),

      _13080000("13080000", "Solution for bee-hive solution"),

      _13082000("13082000", "Bee-hive dispersion"),

      _13084000("13084000", "Oral spray, suspension"),

      _13085000("13085000", "Concentrate for concentrate for oral spray, suspension"),

      _13087000("13087000", "Oculonasal suspension"),

      _13089000("13089000", "Lyophilisate for oral spray, suspension"),

      _13091000("13091000", "Emulsion for suspension for injection"),

      _13096000("13096000", "Nasal spray, lyophilisate for suspension"),

      _13098000("13098000", "Lyophilisate for oculonasal suspension/use in drinking water"),

      _13099000("13099000", "Powder for bee-hive dispersion"),

      _13100000("13100000", "Solution for bee-hive dispersion"),

      _13102000("13102000", "Transdermal ointment"),

      _13105000("13105000", "Sublingual powder"),

      _13106000("13106000", "Oral herbal material"),

      _13107000("13107000", "Solution for cardioplegia/organ preservation"),

      _13111000("13111000", "Powder for vaginal solution"),

      _13113000("13113000", "Intrauterine gel"),

      _13115000("13115000", "Medicinal leech"),

      _13116000("13116000", "Lyophilisate for emulsion for injection"),

      _13118000("13118000", "Tablet with sensor"),

      _13123000("13123000", "Urethral ointment"),

      _13124000("13124000", "Medicinal larvae"),

      _13126000("13126000", "Prolonged-release dispersion for injection"),

      _13127000("13127000", "Sublingual lyophilisate"),

      _13128000("13128000", "Prolonged-release wound solution"),

      _13129000("13129000", "Nebuliser dispersion"),

      _13133000("13133000", "Gastro-resistant oral suspension"),

      _13134000("13134000", "Prolonged-release oral suspension"),

      _13135000("13135000", "Modified-release oral suspension"),

      _13136000("13136000", "Gastro-resistant powder for oral suspension"),

      _13139000("13139000", "Concentrate for dispersion for injection"),

      _13140000("13140000", "Cutaneous/oromucosal solution"),

      _13141000("13141000", "Oromucosal pouch"),

      _13145000("13145000", "Impregnated cutaneous swab"),

      _13148000("13148000", "Prolonged-release pessary"),

      _13149000("13149000", "Oromucosal film"),

      _13152000("13152000", "Concentrate for emulsion for injection"),

      _13154000("13154000", "Film-coated granules"),

      _13158000("13158000", "Effervescent tablet for oculonasal suspension"),

      _13159000("13159000", "Eye drops, prolonged-release solution"),

      _13162000("13162000", "Concentrate for cutaneous emulsion"),

      _13163000("13163000", "Granules for use in drinking water/milk"),

      _30047500("30047500", "Pouch"),

      _50001000("50001000", "Chewable/dispersible tablet"),

      _50009000("50009000", "Concentrate for cutaneous spray, emulsion"),

      _50009300("50009300", "Concentrate for dispersion for infusion"),

      _50009500("50009500", "Concentrate for emulsion for infusion"),

      _50009750("50009750", "Concentrate for intravesical solution"),

      _50010000("50010000", "Concentrate for oral solution"),

      _50011000("50011000", "Concentrate for oral/rectal solution"),

      _50012000("50012000", "Concentrate for peritoneal dialysis solution"),

      _50013000("50013000", "Concentrate for solution for intravesical use"),

      _50013250("50013250", "Concentrate for solution for peritoneal dialysis"),

      _50013500("50013500", "Concentrate for spray emulsion"),

      _50014000("50014000", "Concentrate for suspension for infusion"),

      _50015000("50015000", "Cutaneous and nasal ointment"),

      _50015100("50015100", "Cutaneous/ear drops suspension"),

      _50015200("50015200", "Cutaneous/nasal ointment"),

      _50015300("50015300", "Cutaneous/oromucosal/oral solution"),

      _50015400("50015400", "Cutaneous/oromucosal spray"),

      _50015450("50015450", "Cutaneous solution/concentrate for oromucosal solution"),

      _50015500("50015500", "Cutaneous spray, emulsion"),

      _50016000("50016000", "Cutaneous spray, ointment"),

      _50017000("50017000", "Dental paste"),

      _50017500("50017500", "Dispersion for infusion"),

      _50018000("50018000", "Ear/eye drops, solution"),

      _50018500("50018500", "Ear/eye drops, suspension"),

      _50019000("50019000", "Ear/eye ointment"),

      _50019500("50019500", "Ear/eye/nasal drops, solution"),

      _50020000("50020000", "Ear/eye/nose drops, solution"),

      _50020200("50020200", "Ear/nasal drops, suspension"),

      _50020500("50020500", "Effervescent buccal tablet"),

      _50021000("50021000", "Emulsion for injection/infusion"),

      _50022000("50022000", "Endosinusial wash, suspension"),

      _50023500("50023500", "Film coated gastro-resistant tablet"),

      _50024000("50024000", "Gargle/mouthwash"),

      _50024500("50024500", "Gargle/nasal wash"),

      _50025000("50025000", "Gastro-resistant coated tablet"),

      _50026000("50026000", "Gastro-resistant granules for oral suspension"),

      _50026250("50026250", "Gastro-resistant prolonged-release tablet"),

      _50028000("50028000", "Granules for oral and rectal suspension"),

      _50029000("50029000", "Granules for oral drops, solution"),

      _50029150("50029150", "Granules for oral/rectal suspension"),

      _50029250("50029250", "Granules for use in drinking water"),

      _50029500("50029500", "Granules for vaginal solution"),

      _50029600("50029600", "Hard capsule with gastro-resistant pellets"),

      _50029800("50029800", "Inhalation impregnated pad"),

      _50030000("50030000", "Inhalation powder, tablet"),

      _50031000("50031000", "Inhalation vapour, effervescent tablet"),

      _50032000("50032000", "Inhalation vapour, emulsion"),

      _50033000("50033000", "Inhalation vapour, impregnated pad"),

      _50033100("50033100", "Inhalation vapour, impregnated plug"),

      _50033300("50033300", "Intrauterine foam"),

      _50033400("50033400", "Intravesical solution/solution for injection"),

      _50034000("50034000", "Liquefied gas for dental use"),

      _50034700("50034700", "Lyophilisate for use in drinking water"),

      _50035000("50035000", "Modified-release film-coated tablet"),

      _50036000("50036000", "Modified-release granules for oral suspension"),

      _50036050("50036050", "Mouthwash, powder for solution"),

      _50036100("50036100", "Muco-adhesive buccal prolonged-release tablet"),

      _50036500("50036500", "Nasal/oromucosal solution"),

      _50036700("50036700", "Nasal/oromucosal spray, solution"),

      _50037000("50037000", "Nasal spray and oromucosal solution"),

      _50037100("50037100", "Nasal spray, powder for solution"),

      _50037400("50037400", "Nasal spray, solution/oromucosal solution"),

      _50037500("50037500", "Oral drops, granules for solution"),

      _50037750("50037750", "Oral drops, liquid"),

      _50037900("50037900", "Oral/rectal solution"),

      _50038000("50038000", "Oral/rectal suspension"),

      _50038500("50038500", "Oral solution/concentrate for nebuliser solution"),

      _50039000("50039000", "Oromucosal patch"),

      _50039500("50039500", "Oromucosal/laryngopharyngeal solution"),

      _50040000("50040000", "Oromucosal/laryngopharyngeal solution/spray"),

      _50040500("50040500", "Oromucosal/laryngopharyngeal solution/spray, solution"),

      _50043000("50043000", "Powder for concentrate for solution for infusion"),

      _50048750("50048750", "Powder for concentrate for dispersion for infusion"),

      _50049000("50049000", "Powder for concentrate for haemodialysis solution"),

      _50049100("50049100", "Powder for concentrate for intravesical suspension"),

      _50049200("50049200", "Powder for concentrate for solution for haemodialysis"),

      _50049250("50049250", "Powder for concentrate for solution for injection/infusion"),

      _50049270("50049270", "Powder for dental solution"),

      _50049300("50049300", "Powder for epilesional solution"),

      _50049500("50049500", "Powder for implantation suspension"),

      _50050000("50050000", "Powder for intravesical solution"),

      _50050500("50050500", "Powder for intravesical solution/solution for injection"),

      _50051000("50051000", "Powder for intravesical suspension"),

      _50051100("50051100", "Powder for mouth wash"),

      _50051500("50051500", "Powder for nebuliser solution/solution for injection/infusion"),

      _50052000("50052000", "Powder for oral/rectal suspension"),

      _50053000("50053000", "Powder for solution for injection or infusion"),

      _50053500("50053500", "Powder for solution for injection/infusion"),

      _50054000("50054000", "Powder for solution for intravesical use"),

      _50055000("50055000", "Powder for solution for nasal spray"),

      _50055150("50055150", "Powder for solution/suspension for injection"),

      _50055250("50055250", "Powder for use in drinking water/milk"),

      _50055500("50055500", "Prolonged-release film-coated tablet"),

      _50056000("50056000", "Prolonged-release granules for oral suspension"),

      _50056500("50056500", "Radiopharmaceutical precursor, solution"),

      _50057000("50057000", "Solution for haemodialysis/haemofiltration"),

      _50058000("50058000", "Solution for infusion and oral solution"),

      _50059000("50059000", "Solution for injection/concentrate for solution for infusion"),

      _50059500("50059500", "Solution for injection for euthanasia"),

      _50060000("50060000", "Solution for injection/infusion"),

      _50060700("50060700", "Solution for injection/infusion/rectal use"),

      _50061000("50061000", "Solution for intraperitoneal use"),

      _50061300("50061300", "Solution for use in drinking water"),

      _50061500("50061500", "Solution for sealant"),

      _50061600("50061600", "Solvent for nasal use"),

      _50063000("50063000", "Suspension for infusion"),

      _50063500("50063500", "Suspension for use in drinking water"),

      _50066000("50066000", "Tablet for oral suspension"),

      _50068000("50068000", "Teat dip/spray solution"),

      _50070000("50070000", "Oral suspension for use in drinking water"),

      _50072000("50072000", "Powder for use in drinking water"),

      _50073000("50073000", "Powder for solution for intraocular irrigation"),

      _50073500("50073500", "Solution for intraocular irrigation"),

      _50074000("50074000", "Solvent for solution for intraocular irrigation"),

      _50076000("50076000", "Solvent for solution for infusion"),

      _50077000("50077000", "Dispersion for injection"),

      _50079000("50079000", "Concentrate for solution for injection/infusion"),

      _50081000("50081000", "Inhalation solution"),

      _50082000("50082000", "Oral drops, powder for suspension"),

      _20001000("20001000", "Auricular use"),

      _20002500("20002500", "Buccal use"),

      _20003000("20003000", "Cutaneous use"),

      _20004000("20004000", "Dental use"),

      _20006000("20006000", "Endocervical use"),

      _20007000("20007000", "Endosinusial use"),

      _20008000("20008000", "Endotracheopulmonary use"),

      _20009000("20009000", "Epidural use"),

      _20010000("20010000", "Epilesional use"),

      _20011000("20011000", "Extraamniotic use"),

      _20011500("20011500", "Extracorporeal use"),

      _20087000("20087000", "Extrapleural use"),

      _20013000("20013000", "Gastroenteral use"),

      _20013500("20013500", "Gastric use"),

      _20014000("20014000", "Gingival use"),

      _20015000("20015000", "Haemodialysis"),

      _20015500("20015500", "Implantation"),

      _20019500("20019500", "Infiltration"),

      _20020000("20020000", "Inhalation use"),

      _20021000("20021000", "Intestinal use"),

      _20022000("20022000", "Intraamniotic use"),

      _20023000("20023000", "Intraarterial use"),

      _20024000("20024000", "Intraarticular use"),

      _20025000("20025000", "Intrabursal use"),

      _20025500("20025500", "Intracameral use"),

      _20026000("20026000", "Intracardiac use"),

      _20026500("20026500", "Intracartilaginous use"),

      _20027000("20027000", "Intracavernous use"),

      _20027010("20027010", "Intracerebral use"),

      _20028000("20028000", "Intracervical use"),

      _20028300("20028300", "Intracholangiopancreatic use"),

      _20028500("20028500", "Intracisternal use"),

      _20029000("20029000", "Intracoronary use"),

      _20030000("20030000", "Intradermal use"),

      _20031000("20031000", "Intradiscal use"),

      _20031500("20031500", "Intraepidermal use"),

      _20031700("20031700", "Intraglandular use"),

      _20032000("20032000", "Intralesional use"),

      _20033000("20033000", "Intralymphatic use"),

      _20035000("20035000", "Intramuscular use"),

      _20036000("20036000", "Intraocular use"),

      _20036500("20036500", "Intraosseous use"),

      _20037000("20037000", "Intrapericardial use"),

      _20038000("20038000", "Intraperitoneal use"),

      _20039000("20039000", "Intrapleural use"),

      _20039200("20039200", "Intraportal use"),

      _20039500("20039500", "Intraprostatic use"),

      _20041000("20041000", "Intrasternal use"),

      _20042000("20042000", "Intrathecal use"),

      _20043000("20043000", "Intratumoral use"),

      _20044000("20044000", "Intrauterine use"),

      _20045000("20045000", "Intravenous use"),

      _20046000("20046000", "Intravesical use"),

      _20047000("20047000", "Intravitreal use"),

      _20047500("20047500", "Iontophoresis"),

      _20048000("20048000", "Laryngopharyngeal use"),

      _20049000("20049000", "Nasal use"),

      _20051000("20051000", "Ocular use"),

      _20053000("20053000", "Oral use"),

      _20054000("20054000", "Oromucosal use"),

      _20055000("20055000", "Oropharyngeal use"),

      _20057000("20057000", "Periarticular use"),

      _20058000("20058000", "Perineural use"),

      _20059000("20059000", "Periodontal use"),

      _20059300("20059300", "Periosseous use"),

      _20059400("20059400", "Peritumoral use"),

      _20059500("20059500", "Posterior juxtascleral use"),

      _20061000("20061000", "Rectal use"),

      _20061500("20061500", "Retrobulbar use"),

      _20062000("20062000", "Route of administration not applicable"),

      _20063000("20063000", "Skin scarification"),

      _20065000("20065000", "Subconjunctival use"),

      _20066000("20066000", "Subcutaneous use"),

      _20067000("20067000", "Sublingual use"),

      _20067500("20067500", "Submucosal use"),

      _20070000("20070000", "Transdermal use"),

      _20071000("20071000", "Urethral use"),

      _20072000("20072000", "Vaginal use"),

      _20080000("20080000", "Intracerebroventricular use"),

      _20081000("20081000", "Subretinal use"),

      _20084000("20084000", "Intracorneal use"),

      _20086000("20086000", "Intraputaminal use");

      private final @NonNull String code;

      private final @Nullable String display;

      EdqmStandardterms(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     http://standardterms.edqm.eu}
       */
      public @NonNull Coding coding() {
        return new Coding("http://standardterms.edqm.eu", code, display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull EdqmStandardterms> fromValue(@NonNull String code) {
        for (EdqmStandardterms value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }
    }
  }
}
