// Generated by ig-codegen from KBV-CS-SFHIR-BMP-DARREICHUNGSFORM 1.03. Do not edit directly.
package io.github.dizuker.medrezeptetofhir.kbv;

import org.hl7.fhir.r4.model.Coding;

public final class KbvDarreichungsform {
  private KbvDarreichungsform() {}

  public static final class CodeSystems {
    private CodeSystems() {}

    /**
     * The canonical URL {@code https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_BMP_DARREICHUNGSFORM}.
     *
     * @return {@code https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_BMP_DARREICHUNGSFORM}
     */
    public static String kbvCsSfhirBmpDarreichungsform() {
      return "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_BMP_DARREICHUNGSFORM";
    }

    public enum KbvCsSfhirBmpDarreichungsform {
      AEO("AEO", "Öl"),

      AMP("AMP", "Amp"),

      APA("APA", "Amp"),

      ASN("ASN", "Salbe"),

      ASO("ASO", "Salbe"),

      ATO("ATO", "Tropf"),

      ATR("ATR", "AuTropf"),

      AUB("AUB", "AuBad"),

      AUC("AUC", "AuCreme"),

      AUG("AUG", "AuGel"),

      AUS("AUS", "AuSalbe"),

      BAD("BAD", "Bad"),

      BAL("BAL", "Balsam"),

      BAN("BAN", "Bandage"),

      BEU("BEU", "Beutel"),

      BIN("BIN", "Binden"),

      BON("BON", "Bonbons"),

      BPL("BPL", "Platte"),

      BRE("BRE", "Brei"),

      BTA("BTA", "BrTabl"),

      CRE("CRE", "Creme"),

      DFL("DFL", "Flasche"),

      DIL("DIL", "Dilut"),

      DIS("DIS", "DIS"),

      DKA("DKA", "Dragees"),

      DOS("DOS", "Spray"),

      DRA("DRA", "Dragees"),

      DRM("DRM", "Dragees"),

      DSC("DSC", "Schaum"),

      DSS("DSS", "Spray"),

      EDP("EDP", "Pipette"),

      EIN("EIN", "Einreib"),

      ELE("ELE", "Elektr"),

      ELI("ELI", "Elixier"),

      EMU("EMU", "Emul"),

      ESS("ESS", "Essenz"),

      ESU("ESU", "Supp"),

      EXT("EXT", "Extrakt"),

      FBE("FBE", "Beutel"),

      FBW("FBW", "Einreib"),

      FDA("FDA", "Drag"),

      FER("FER", "Spritze"),

      FET("FET", "Salbe"),

      FLA("FLA", "Flasche"),

      FLE("FLE", "Flüss"),

      FLU("FLU", "Flüss"),

      FMR("FMR", "Tabl"),

      FOL("FOL", "Folie"),

      FRB("FRB", "FRB"),

      FSE("FSE", "Seife"),

      FTA("FTA", "Tabl"),

      GEK("GEK", "Gran"),

      GEL("GEL", "Gel"),

      GLI("GLI", "GLI"),

      GLO("GLO", "Globuli"),

      GMR("GMR", "Gran"),

      GPA("GPA", "Platte"),

      GRA("GRA", "Gran"),

      GSE("GSE", "Saft"),

      GUL("GUL", "Lösung"),

      HAS("HAS", "Handsch"),

      HKM("HKM", "Kaps"),

      HKP("HKP", "Kaps"),

      HPI("HPI", "InhKaps"),

      HVW("HVW", "Kaps"),

      IFA("IFA", "Amp"),

      IFB("IFB", "Beutel"),

      IFD("IFD", "InfDisp"),

      IFE("IFE", "Spritze"),

      IFF("IFF", "Flasche"),

      IFK("IFK", "Lösung"),

      IFL("IFL", "Flasche"),

      IFS("IFS", "Set"),

      IHA("IHA", "InhAmp"),

      IHP("IHP", "InhPulv"),

      IIE("IIE", "Lösung"),

      IIL("IIL", "Lösung"),

      IIM("IIM", "Lösung"),

      IKA("IKA", "InhKaps"),

      ILO("ILO", "Lösung"),

      IMP("IMP", "Impl"),

      INF("INF", "Lösung"),

      INH("INH", "Inhalat"),

      INI("INI", "Flasche"),

      INL("INL", "InhLös"),

      INS("INS", "Tee"),

      IST("IST", "Instill"),

      ISU("ISU", "Susp"),

      IUP("IUP", "Spirale"),

      KAN("KAN", "Kanüle"),

      KAP("KAP", "Kaps"),

      KAT("KAT", "KAT"),

      KDA("KDA", "KauDrag"),

      KEG("KEG", "Kegel"),

      KER("KER", "Kerne"),

      KGU("KGU", "Kaug"),

      KID("KID", "Konz"),

      KII("KII", "Konz"),

      KKS("KKS", "Supp"),

      KLI("KLI", "Klist"),

      KLT("KLT", "KlisTbl"),

      KMP("KMP", "Kaps"),

      KMR("KMR", "Kaps"),

      KOD("KOD", "Kondom"),

      KOM("KOM", "Kompr"),

      KON("KON", "Konz"),

      KPG("KPG", "KombiPg"),

      KRI("KRI", "KRI"),

      KSS("KSS", "Supp"),

      KSU("KSU", "Supp"),

      KTA("KTA", "KauTabl"),

      LAN("LAN", "Lanz"),

      LII("LII", "Lösung"),

      LIQ("LIQ", "Flüss"),

      LOE("LOE", "Lösung"),

      LOT("LOT", "Lotion"),

      LOV("LOV", "LOV"),

      LSE("LSE", "Lösung"),

      LTA("LTA", "Tabl"),

      LUP("LUP", "LUP"),

      LUT("LUT", "LuTabl"),

      MIL("MIL", "Milch"),

      MIS("MIS", "Misch"),

      MIX("MIX", "Mixtur"),

      MRG("MRG", "RetGran"),

      MRP("MRP", "Pellets"),

      MTA("MTA", "Tabl"),

      MUW("MUW", "MUW"),

      NAG("NAG", "NasGel"),

      NAO("NAO", "NasÖl"),

      NAS("NAS", "NasSpr"),

      NAW("NAW", "NAW"),

      NDS("NDS", "NasSpr"),

      NSA("NSA", "NSalbe"),

      NTR("NTR", "NTropf"),

      OCU("OCU", "OCU"),

      OEL("OEL", "Öl"),

      OHT("OHT", "OTropf"),

      OVU("OVU", "Ovula"),

      PAS("PAS", "Pastill"),

      PEL("PEL", "Pellets"),

      PEN("PEN", "Pen"),

      PER("PER", "Perlen"),

      PFL("PFL", "Pflast"),

      PFT("PFT", "Pflast"),

      PHI("PHI", "Pulver"),

      PHV("PHV", "Pulver"),

      PIE("PIE", "Pulver"),

      PIF("PIF", "Lösung"),

      PII("PII", "Pulver"),

      PIJ("PIJ", "Pulver"),

      PIK("PIK", "Pulver"),

      PIS("PIS", "Pulver"),

      PIV("PIV", "PIV"),

      PKI("PKI", "Pulver"),

      PLE("PLE", "Pulver"),

      PLF("PLF", "PLF"),

      PLG("PLG", "PLG"),

      PLH("PLH", "PLH"),

      PLI("PLI", "PLI"),

      PLK("PLK", "PLK"),

      PLS("PLS", "Pulver"),

      PLV("PLV", "PLV"),

      PPL("PPL", "Lösung"),

      PRS("PRS", "PRS"),

      PSE("PSE", "Saft"),

      PST("PST", "Paste"),

      PUD("PUD", "Puder"),

      PUL("PUL", "Pulver"),

      RED("RED", "RetDrag"),

      REK("REK", "RetKaps"),

      RET("RET", "RetTabl"),

      RGR("RGR", "RetGran"),

      RKA("RKA", "RekKaps"),

      RMS("RMS", "Depot"),

      RSC("RSC", "Schaum"),

      RSU("RSU", "RekSusp"),

      RUT("RUT", "RetTabl"),

      SAF("SAF", "Saft"),

      SAL("SAL", "Salbe"),

      SAM("SAM", "Salbe"),

      SCH("SCH", "Schaum"),

      SEI("SEI", "Seife"),

      SHA("SHA", "Shampoo"),

      SIR("SIR", "Sirup"),

      SMF("SMF", "SMF"),

      SMT("SMT", "SMT"),

      SMU("SMU", "Supp"),

      SPA("SPA", "Amp"),

      SPF("SPF", "Flasche"),

      SPL("SPL", "Lösung"),

      SPR("SPR", "Spray"),

      SPT("SPT", "Spray"),

      SRI("SRI", "Spritze"),

      SSU("SSU", "Supp"),

      STA("STA", "Amp"),

      STB("STB", "Stäbch"),

      STI("STI", "Stifte"),

      STR("STR", "Streif"),

      SUB("SUB", "Subst"),

      SUE("SUE", "Susp"),

      SUL("SUL", "SubSpr"),

      SUP("SUP", "Supp"),

      SUS("SUS", "Susp"),

      SUT("SUT", "SubTabl"),

      SUV("SUV", "Susp"),

      SWA("SWA", "Schwamm"),

      TAB("TAB", "Tabl"),

      TAE("TAE", "Tafel"),

      TAM("TAM", "Amp"),

      TEE("TEE", "Tee"),

      TEI("TEI", "Tropfen"),

      TES("TES", "Test"),

      TIN("TIN", "Tinktur"),

      TKA("TKA", "Tabl"),

      TLE("TLE", "LösTabl"),

      TMR("TMR", "Tabl"),

      TON("TON", "Tonikum"),

      TPN("TPN", "Tampon"),

      TPO("TPO", "Tamp"),

      TRA("TRA", "TrAmp"),

      TRI("TRI", "TRI"),

      TRO("TRO", "Tropfen"),

      TRS("TRS", "TRS"),

      TRT("TRT", "TrTabl"),

      TSA("TSA", "Saft"),

      TSD("TSD", "TSD"),

      TSE("TSE", "SusTabl"),

      TSS("TSS", "TSS"),

      TST("TST", "Test"),

      TSY("TSY", "TSY"),

      TTR("TTR", "Test"),

      TUB("TUB", "Tube"),

      TUE("TUE", "Tücher"),

      TUP("TUP", "Tupfer"),

      TVW("TVW", "RetTabl"),

      UTA("UTA", "Tabl"),

      VAL("VAL", "VagLös"),

      VAR("VAR", "VagRing"),

      VCR("VCR", "VagCrem"),

      VER("VER", "Verband"),

      VGE("VGE", "VagGel"),

      VKA("VKA", "VagKaps"),

      VLI("VLI", "Vlies"),

      VOV("VOV", "VagOvul"),

      VST("VST", "VagStäb"),

      VSU("VSU", "VagSupp"),

      VTA("VTA", "VagTabl"),

      WAT("WAT", "Watte"),

      WGA("WGA", "Gaze"),

      WKA("WKA", "Kaps"),

      WKM("WKM", "Kaps"),

      WUE("WUE", "Würfel"),

      XDG("XDG", "Gel"),

      XDS("XDS", "Spray"),

      XFE("XFE", "Festig."),

      XGM("XGM", "Maske"),

      XHS("XHS", "Spül."),

      XNC("XNC", "Creme"),

      XPK("XPK", "Pflege"),

      XTC("XTC", "Creme"),

      ZAM("ZAM", "Amp"),

      ZBU("ZBU", "Bürste"),

      ZCR("ZCR", "Zahncr."),

      ZGE("ZGE", "Zahngel"),

      ZKA("ZKA", "ZerbKps"),

      ZPA("ZPA", "Zahnp.");

      private final String code;

      private final String display;

      KbvCsSfhirBmpDarreichungsform(String code, String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_BMP_DARREICHUNGSFORM}
       */
      public Coding coding() {
        return new Coding(
            "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_BMP_DARREICHUNGSFORM", code, display);
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} equals {@code code}
       * @throws IllegalArgumentException if no constant has that code
       */
      public static KbvCsSfhirBmpDarreichungsform fromValue(String code) {
        for (KbvCsSfhirBmpDarreichungsform value : values()) {
          if (value.code.equals(code)) {
            return value;
          }
        }
        throw new IllegalArgumentException("Unknown code: " + code);
      }
    }
  }
}
