name: validate-fhir-resources

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  validate-fhir-resource:
    name: validate fhir resources
    runs-on: ubuntu-24.04
    container: ghcr.io/miracum/ig-build-tools:v2.2.46@sha256:00ab42bcf4f527b5c4f7415dc8bbcd65aa05f21f5ddfa4303bdaf7642789d862
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Configure fhir cli
        run: |
          fhir config inflate All
          fhir config validator Advanced

      - name: Cache FHIR packages
        id: fhir-package-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            /github/home/.fhir/packages
            fhirpkg.lock.json
          key: fhir-packages-${{ hashFiles('package.json') }}
          restore-keys: |
            fhir-packages-

      - name: Restore FHIR package dependencies
        if: ${{ steps.fhir-package-cache.outputs.cache-hit != 'true' }}
        run: |
          fhir cache location --path
          fhir cache list
          fhir restore

      - name: Validate bundles
        continue-on-error: true
        run: |
          fhir cache location --path
          fhir cache list
          find src/test/java/snapshots/ -type f \
            -name "*.fhir.json" -print0 | \
            xargs -0 -I {} sh -c 'echo "\n\n\nValidating: {}" && fhir validate --verbose --fail "{}"'
