name: validate-fhir-resources

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  validate-fhir-resource:
    name: validate fhir resources
    runs-on: ubuntu-24.04
    container: ghcr.io/miracum/ig-build-tools:v2.3.0@sha256:c849d2e22b6088ef191202763170553de88cafd4907a6f9d0e11e5b0ff7e83ef
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configure fhir cli
        run: |
          fhir config inflate All
          fhir config validator Advanced

      - name: Cache FHIR packages
        id: fhir-package-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            /github/home/.fhir/packages
            fhirpkg.lock.json
          key: fhir-packages-${{ hashFiles('package.json') }}
          restore-keys: |
            fhir-packages-

      - name: Restore FHIR package dependencies
        if: ${{ steps.fhir-package-cache.outputs.cache-hit != 'true' }}
        run: |
          fhir cache location --path
          fhir cache list
          fhir restore

      - name: Validate bundles
        continue-on-error: true
        run: |
          fhir cache location --path
          fhir cache list
          find src/test/java/snapshots/ -type f \
            -name "*.fhir.json" -print0 | \
            xargs -0 -I {} sh -c 'echo "\n\n\nValidating: {}" && fhir validate --verbose --fail "{}"'
